### PR TITLE
Waves

### PR DESCRIPTION
**Pull request by schoero**
@bahamut657, @fivdi

I continued to work on the wave functions and made lots of changes and improvements to them. For example:

* Simplified function parameters
* Completed documentation
* Added and simplified examples
* Added tests
* Removed watchdog and serial functions

I have verified all examples and tests with an oscilloscope and have used the wave functions for quite a while now on some personal projects to send infrared codes.

I read all the comments from the original pull request https://github.com/fivdi/pigpio/pull/64 and I think i have fixed everything that was mentioned so far.

Roger

### CODE REVIEW

**Comment by fivdi** [comment]
@Rogerrrrrrrs @bahamut657 

Hi, I just installed Rogerrrrrrrs/pigpio#Waves with the command `npm i Rogerrrrrrrs/pigpio#Waves` on a Raspberry Pi 4 with Node.js v12.14.0 and it looks very promising. The examples functioned correctly and the tests worked most of the time (sometimes waves-add test hangs, I don't know why.) An initial scan of the code and documentation also looked good.

I'm not sure what needs to be done to create PR at fivid/pigpio but if you create such a PR I'd take a closer look and would be very interested in merging. Please ensure that the PR at fivdi/pigpio only contains the required changes. For example, this PR here contains a lot of PRs from myself and others that shouldn't be there. I'm not a git expert and not sure what needs to be done to fix this. Perhaps @bahamut657 just needs to merge this PR, but I could be wrong.

**Comment by schoero** [comment]
@fivdi 

> sometimes waves-add test hangs, I don't know why.

Thank you for pointing this out. I've found out that the first two pulses (1μs and 2μs) sometimes didn't got captured by the alert event. But I can confirm with the oscilloscope that they were always sent correctly.

> Perhaps @bahamut657 just needs to merge this PR, but I could be wrong.

As I understood, if @bahamut657 would merge the PR, I would be able to commit directly into his upstream PR. 
I will remove the unwanted commits and fix the tests, if @bahamut657 doesn't merge the PR until I'm finished, i will just go ahead and create my own PR.

**Comment by schoero** [comment]
@fivdi 
I tried to remove the foreign commits and cherry-pick only the waves related commits but that does not really work since lots of the early commits are messy.

I either suggest to leave the foreign commits in, (I think it should cause no problems when merging, because those commits where just updates from the master branch into the wave branches), or that I create a completly new branch from the current codebase and then reapply the wave related changes with own commits. That would be much easier but the commit history would get lost.
Are you OK with that?

**Comment by bahamut657** [comment]
I just confirmed your PR in order to permit the merge on the main branch.

**Comment by schoero** [comment]
Thank you @bahamut657, but I was wrong. Only the commits prior to the merge went into your PR, new commits do not get added. I will probably create my own PR now, but I want to await the opinion from @fivdi regarding my commit problem I mentioned above.

**Comment by fivdi** [comment]
@bahamut657 @Rogerrrrrrrs Thank you both for working on this.

Please take a look at https://github.com/fivdi/pigpio/pull/64/files. Does it look good to you? It looks like it contains the required commits and only the required commits to me. Is this the correct?

**Comment by schoero** [comment]
Thank you @fivdi 
It looks good to me, i think i misunderstood you about the commits. Nevertheless I still have to make my own pull request to be able to add commits without making pull requests to @bahamut657 all the time. I will doublecheck everything tomorrow and make a proper PR.

**Pull request merged**
